version: '3'
services: 
  elasticsearch:
    image: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300        

  ptt-crawler:        
    build: 
      context: .
      dockerfile: Dockerfile        
    container_name: ptt-crawler          
    volumes:
      - /tmp:/opt/ptt-crawler/tmp      
    tty: true    

